### ISSUE TITLE
Rename calibration file for kinects

### ISSUE THREAD

**Issue by NadiaHG** [ipa320/cob_calibration#10]
The name of the yaml calibration data for kinects should be the name of the camera, for example for cob3 should be cam3d.yaml instead of kinect_rgb.yaml

**Comment by fmessmer** [comment]
~~could be considered together with https://github.com/ipa320/cob_robots/issues/372~~

**Comment by fmessmer** [comment]
However, I think the whole package needs an overhaul as it is not working with any robot other than cob3-3!
Still the suggestion makes sense and should be applied to cob_calibration_data!

**Comment by fmessmer** [comment]
should be done after #12

**Comment by fmessmer** [comment]
I can't remember the rationale behind this
only calibration files for cameras currently used is `head_cam.yaml` for the usb_cam
